defaults: &defaults
  image:
    default_poster: "/uploads/poster/course.jpg"
    default_avatar: "/uploads/avatar/avatar.jpg"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
